import BriefRepository
import DomainModels

/// The single source of truth for the "This Week" screen's lifecycle (PRD §8.2, DECISIONS #1) — a closed
/// enum switched **exhaustively** (no `default:`) in the reducer and view, mirroring the shipped
/// `TodayFeature` universal-lifecycle-enum (`BriefViewState`) but scoped to weekly: there is **no** sync
/// step (the app-open sync runs upstream in `AppFeature`'s chain, §11).
///
/// `idle → loading → ready(fresh|cached) → error`. `deload`, a `nil` `longRunKm`, the core/extra sessions
/// (Phase 9.2), and the weekly nutrition (Phase 9.3) are all **content of a `ready` plan**, not separate
/// lifecycle cases (DECISIONS #1) — later phases add their rendering to `ready`, never new cases, so the
/// closed enum stays stable and exhaustively switched. The `error` terminal carries the typed
/// `BriefError` as-is; the human copy + Retry affordance is the `DesignSystem` presentation boundary's job.
public enum WeeklyViewState: Equatable, Sendable {
  case idle
  /// Fetching / generating the weekly plan.
  case loading
  /// A resolved plan + whether it was generated by this request (`.fresh`) or served from the per-ISO-week
  /// cache (`.cached`, the "as of …" label).
  case ready(DomainModels.WeeklyPlan, Freshness)
  /// A generation / transport / sync-required failure.
  case error(BriefError)

  /// Whether a resolved plan is on screen — the pull-to-refresh gate (`WeeklyView` attaches the gesture
  /// only over `.ready`, and its spinner-hold poll exits the moment the state leaves `.ready`).
  public var isReady: Bool {
    if case .ready = self { return true }
    return false
  }
}

/// Whether a `ready` plan was served fresh (this request generated it) or from the per-ISO-week cache
/// (PRD §8.2 — the `cached` flag drives the "as of …" label, never a spinner decision).
public enum Freshness: Equatable, Sendable { case fresh, cached }
